template_path: gateway-vpc-endpoint.yaml
stack_name: s3-gateway-vpc-endpoint
dependencies:
  - prod/sandcastlevpc.yaml
parameters:
  VpcName: sandcastlevpc
  ServiceName: com.amazonaws.us-east-1.s3
hooks:
  before_update:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/gateway-vpc-endpoint.yaml --create-dirs -o templates/remote/gateway-vpc-endpoint.yaml"
