template_path: "remote/transit-gateway-spoke.yaml"
stack_name: "tgw-spoke-sandcastlevpc"
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
dependencies:
  - "prod/essentials.yaml"
  - "prod/sandcastlevpc.yaml"
parameters:
  TransitGatewayId: "tgw-00d248c4cfce0d06e"     # shared TGW from org-sagebase-transit
  TransitGatewayEndpointCidr: "10.50.0.0/16"
  VpcRouteTableId: !stack_output_external sandcastlevpc::PrivateRouteTable
  VpcId: !stack_output_external sandcastlevpc::VPCId
  SubnetIds:
    - !stack_output_external sandcastlevpc::PrivateSubnet
    - !stack_output_external sandcastlevpc::PrivateSubnet1
    - !stack_output_external sandcastlevpc::PrivateSubnet2
hooks:
  before_launch:
    - !cmd "curl https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/master/transit-gateway-spoke.yaml --create-dirs -o templates/remote/transit-gateway-spoke.yaml"
