Description: Setup IAM policies, groups and accounts
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  InitNewUserPassword:
    Type: String
    NoEcho: true
Resources:
  # !! IMPORTANT !! - AWS API will refuse to remove users that have attached resources.
  # Therefore you must do the following before deleting them from this file:
  # 1. Detach or remove the following user resources: login profile, attached
  #    MFA device, access-keys, ssh-keys, and policies.
  # 2. Detach the user from all groups.
  AWSIAMBrianWhiteUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: brian.white@sagebase.org
      Groups:
        - !Ref AWSIAMAllUsersGroup
        - !Ref AWSIAMDeveloperUsersGroup
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  AWSIAMRebeccaElyanowUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: rebecca.elyanow@sagebase.org
      Groups:
        - !Ref AWSIAMAllUsersGroup
        - !Ref AWSIAMDeveloperUsersGroup
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  AWSIAMAndrewLambUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: andrew.lamb@sagebase.org
      Groups:
        - !Ref AWSIAMAllUsersGroup
        - !Ref AWSIAMDeveloperUsersGroup
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  AWSIAMAaronBakerUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: aaron.baker@sagebase.org
      Groups:
        - !Ref AWSIAMAllUsersGroup
        - !Ref AWSIAMDeveloperUsersGroup
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  AWSIAMMilenNikolovUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: milen.nikolov@sagebase.org
      Groups:
        - !Ref AWSIAMAllUsersGroup
        - !Ref AWSIAMDeveloperUsersGroup
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  AWSIAMZimingDongTestUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: ziming.dong@sagebase.org
      Groups:
        - !Ref AWSIAMAllUsersGroup
        - !Ref AWSIAMDeveloperUsersGroup
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  AWSIAMXavierSchildwachterUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: x.schildwachter@sagebase.org
      Groups:
        - !Ref AWSIAMAllUsersGroup
        - !Ref AWSIAMDeveloperUsersGroup
        - !Ref AWSIAMBillingManagersGroup
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  AWSIAMKhaiDoUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: khai.do@sagebase.org
      Groups:
        - !Ref AWSIAMAllUsersGroup
        - !Ref AWSIAMDeveloperUsersGroup
        - !Ref AWSIAMBillingManagersGroup
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  AWSIAMThomasYuUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: thomas.yu@sagebase.org
      Groups:
        - !Ref AWSIAMAllUsersGroup
        - !Ref AWSIAMDeveloperUsersGroup
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  AWSIAMPhilSnyderUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: phil.snyder@sagebase.org
      Groups:
        - !Ref AWSIAMAllUsersGroup
        - !Ref AWSIAMDeveloperUsersGroup
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  AWSIAMKennethDailyUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: kenneth.daily@sagebase.org
      Groups:
        - !Ref AWSIAMAllUsersGroup
        - !Ref AWSIAMDeveloperUsersGroup
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  AWSIAMRobertAllawayUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: robert.allaway@sagebase.org
      Groups:
        - !Ref AWSIAMAllUsersGroup
        - !Ref AWSIAMDeveloperUsersGroup
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  AWSIAMSaraGoslineUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: sara.gosline@sagebase.org
      Groups:
        - !Ref AWSIAMAllUsersGroup
        - !Ref AWSIAMDeveloperUsersGroup
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  AWSIAMXengieDoanUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: xengie.doan@sagebase.org
      Groups:
        - !Ref AWSIAMAllUsersGroup
        - !Ref AWSIAMDeveloperUsersGroup
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  AWSIAMJakeGockleyUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: jake.gockley@sagebase.org
      Groups:
        - !Ref AWSIAMAllUsersGroup
        - !Ref AWSIAMDeveloperUsersGroup
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  AWSIAMThomasSchaffterUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: thomas.schaffter@sagebase.org
      Groups:
        - !Ref AWSIAMAllUsersGroup
        - !Ref AWSIAMDeveloperUsersGroup
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  AWSIAMKimYenLadiaUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: kimyen.ladia@sagebase.org
      Groups:
        - !Ref AWSIAMAllUsersGroup
        - !Ref AWSIAMDeveloperUsersGroup
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  AWSIAMWilliamPoehlmanUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: william.poehlman@sagebase.org
      Groups:
        - !Ref AWSIAMAllUsersGroup
        - !Ref AWSIAMDeveloperUsersGroup
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  AWSIAMTessThyerUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: tess.thyer@sagebase.org
      Groups:
        - !Ref AWSIAMAllUsersGroup
        - !Ref AWSIAMDeveloperUsersGroup
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  AWSIAMAaronHaydenUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: aaron.hayden@sagebase.org
      Groups:
        - !Ref AWSIAMAllUsersGroup
        - !Ref AWSIAMDeveloperUsersGroup
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  # for deployments from Sage-Bionetworks/PHCCollaborationPortal repo
  PhccpServiceUser:
    Type: 'AWS::IAM::User'
  PhccpServiceUserAccessKey:
    Type: 'AWS::IAM::AccessKey'
    Properties:
      UserName: !Ref PhccpServiceUser
  # temporary user for MSSM to transfer files to Sage.
  # console access is disabled, api key to allow access to MSSM bucket
  AWSIAMMssmUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: mssm@sagebase.org
  AWSIAMMssmUserAccessKey:
    Type: 'AWS::IAM::AccessKey'
    Properties:
      UserName: !Ref AWSIAMMssmUser
  AWSIAMDeveloperUsersGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/PowerUserAccess
        - arn:aws:iam::aws:policy/IAMReadOnlyAccess
        - !Ref AWSIAMDynamoDenyDeletePolicy
        - !Ref AWSIAMRdsDenyDeletePolicy
        - arn:aws:iam::aws:policy/AWSCodeDeployFullAccess
  CodeDeployServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              AWS:
                - !GetAtt PhccpServiceUser.Arn
                - !GetAtt AWSIAMThomasSchaffterUser.Arn
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeDeployFullAccess
  AWSIAMAdminRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              AWS:
                - !GetAtt AWSIAMXavierSchildwachterUser.Arn
                - !GetAtt AWSIAMKhaiDoUser.Arn
                - !GetAtt AWSIAMThomasYuUser.Arn
                - !GetAtt AWSIAMTessThyerUser.Arn
                - !GetAtt AWSIAMAaronHaydenUser.Arn
                - !GetAtt AWSIAMKennethDailyUser.Arn
            Action:
              - "sts:AssumeRole"
      Path: "/"
  AWSIAMDynamoDenyDeletePolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Deny
            Action:
              # UpdateTable operation retricts deletion of indexes
              - dynamodb:UpdateTable
              - dynamodb:DeleteTable
            Resource: "*"
  AWSIAMRdsDenyDeletePolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Deny
            Action:
              - rds:DeleteDBCluster
              - rds:DeleteDBClusterSnapshot
              - rds:DeleteDBInstance
              - rds:DeleteDBSnapshot
            Resource: "*"
  AWSIAMOrganizationsFullAccessPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: "Allow"
            Action: "organizations:*"
            Resource: "*"
  AWSIAMAdminRolePolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "admin"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action: "*"
            Resource: "*"
      Roles:
        -
          !Ref AWSIAMAdminRole
  AWSIAMAllUsersGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
        - !Ref AWSIAMEnforceMfaPolicy
  AWSIAMBillingManagersGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/Billing
        - !Ref AWSIAMOrganizationsFullAccessPolicy
  # policy to enforce MFA
  AWSIAMEnforceMfaPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowAllUsersToListAccounts
            Effect: Allow
            Action:
              - 'iam:ListAccountAliases'
              - 'iam:ListUsers'
              - 'iam:GetAccountSummary'
            Resource: '*'
          - Sid: AllowIndividualUserToSeeAndManageOnlyTheirOwnAccountInformation
            Effect: Allow
            Action:
              - 'iam:ChangePassword'
              - 'iam:CreateAccessKey'
              - 'iam:CreateLoginProfile'
              - 'iam:DeleteAccessKey'
              - 'iam:DeleteLoginProfile'
              - 'iam:GetAccountPasswordPolicy'
              - 'iam:GetLoginProfile'
              - 'iam:ListAccessKeys'
              - 'iam:UpdateAccessKey'
              - 'iam:UpdateLoginProfile'
              - 'iam:ListSigningCertificates'
              - 'iam:DeleteSigningCertificate'
              - 'iam:UpdateSigningCertificate'
              - 'iam:UploadSigningCertificate'
              - 'iam:ListSSHPublicKeys'
              - 'iam:GetSSHPublicKey'
              - 'iam:DeleteSSHPublicKey'
              - 'iam:UpdateSSHPublicKey'
              - 'iam:UploadSSHPublicKey'
            Resource: !Join
              - ''
              - - 'arn:aws:iam::'
                - !Ref AWS::AccountId
                - ':user/${aws:username}'
          - Sid: AllowIndividualUserToListOnlyTheirOwnMFA
            Effect: Allow
            Action:
              - 'iam:ListVirtualMFADevices'
              - 'iam:ListMFADevices'
            Resource:
              - !Join
                - ''
                - - 'arn:aws:iam::'
                  - !Ref AWS::AccountId
                  - ':mfa/*'
              - !Join
                - ''
                - - 'arn:aws:iam::'
                  - !Ref AWS::AccountId
                  - ':user/${aws:username}'
          - Sid: AllowIndividualUserToManageTheirOwnMFA
            Effect: Allow
            Action:
              - 'iam:CreateVirtualMFADevice'
              - 'iam:DeleteVirtualMFADevice'
              - 'iam:RequestSmsMfaRegistration'
              - 'iam:FinalizeSmsMfaRegistration'
              - 'iam:EnableMFADevice'
              - 'iam:ResyncMFADevice'
            Resource:
              - !Join
                - ''
                - - 'arn:aws:iam::'
                  - !Ref AWS::AccountId
                  - ':mfa/${aws:username}'
              - !Join
                - ''
                - - 'arn:aws:iam::'
                  - !Ref AWS::AccountId
                  - ':user/${aws:username}'
          - Sid: AllowIndividualUserToDeactivateOnlyTheirOwnMFAOnlyWhenUsingMFA
            Effect: Allow
            Action:
              - 'iam:DeactivateMFADevice'
            Resource:
              - !Join
                - ''
                - - 'arn:aws:iam::'
                  - !Ref AWS::AccountId
                  - ':mfa/${aws:username}'
              - !Join
                - ''
                - - 'arn:aws:iam::'
                  - !Ref AWS::AccountId
                  - ':user/${aws:username}'
            Condition:
              Bool:
                'aws:MultiFactorAuthPresent': 'true'
          - Sid: BlockAnyAccessOtherThanAboveUnlessSignedInWithMFA
            Effect: Deny
            NotAction: 'iam:*'
            Resource: '*'
            Condition:
              BoolIfExists:
                'aws:MultiFactorAuthPresent': 'false'
Outputs:
  AWSIAMEnforceMfaPolicy:
    Value: !Ref AWSIAMEnforceMfaPolicy
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-EnforceMfaPolicy'
  AWSIAMMssmUserAccessKey:
    Value: !Ref AWSIAMMssmUserAccessKey
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-MssmUserAccessKey'
  AWSIAMMssmSecretUserAccessKey:
    Value: !GetAtt AWSIAMMssmUserAccessKey.SecretAccessKey
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-MssmUserSecretAccessKey'
  PhccpServiceUserAccessKey:
    Value: !Ref PhccpServiceUserAccessKey
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-PhccpServiceUserAccessKey'
  PhccpServiceUserSecretAccessKey:
    Value: !GetAtt PhccpServiceUserAccessKey.SecretAccessKey
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-PhccpServiceUserSecretAccessKey'
  CodeDeployServiceRoleArn:
    Value: !GetAtt CodeDeployServiceRole.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-CodeDeployServiceRoleArn'
